# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-21 01:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import sorl.thumbnail.fields
import stats.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fixture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=stats.models.get_next_fixture_date, help_text='Fecha de la jornada', unique=True, verbose_name='Fecha')),
                ('image', sorl.thumbnail.fields.ImageField(blank=True, help_text='Foto de la jornada', upload_to='Jornadas', verbose_name='Foto')),
                ('numero', models.PositiveSmallIntegerField(default=stats.models.get_next_fixture, verbose_name='Jornada número')),
            ],
            options={
                'verbose_name_plural': 'Jornadas',
                'ordering': ['-date'],
                'verbose_name': 'Jornada',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre del jugador', max_length=200, unique=True, verbose_name='Nombre')),
                ('image', sorl.thumbnail.fields.ImageField(blank=True, help_text='Foto del jugador', upload_to='Avatars', verbose_name='Avatar')),
                ('games_played', models.PositiveSmallIntegerField(default=0, verbose_name='Juegos jugados')),
                ('wins', models.PositiveSmallIntegerField(default=0, verbose_name='Juegos ganados')),
                ('draws', models.PositiveSmallIntegerField(default=0, verbose_name='Juegos empatados')),
                ('losses', models.PositiveSmallIntegerField(default=0, verbose_name='Juegos perdidos')),
                ('goals', models.PositiveSmallIntegerField(default=0, verbose_name='Goles anotados')),
                ('assists', models.PositiveSmallIntegerField(default=0, verbose_name='Asistencias')),
                ('elo', models.DecimalField(decimal_places=5, default=0, max_digits=7, verbose_name='ELO')),
            ],
            options={
                'verbose_name_plural': 'Jugadores',
                'ordering': ['-elo'],
                'verbose_name': 'Jugador',
            },
        ),
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('games_played', models.PositiveSmallIntegerField(default=0, verbose_name='Juegos jugados')),
                ('wins', models.PositiveSmallIntegerField(default=0, verbose_name='Juegos ganados')),
                ('draws', models.PositiveSmallIntegerField(default=0, verbose_name='Juegos empatados')),
                ('losses', models.PositiveSmallIntegerField(default=0, verbose_name='Juegos perdidos')),
                ('goals', models.PositiveSmallIntegerField(default=0, verbose_name='Goles anotados')),
                ('assists', models.PositiveSmallIntegerField(default=0, verbose_name='Asistencias')),
                ('elo', models.DecimalField(decimal_places=5, default=0, max_digits=7, verbose_name='ELO')),
                ('fixture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='stats.Fixture', verbose_name='Jornada')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='stats.Player', verbose_name='Jugador')),
            ],
            options={
                'verbose_name_plural': 'Actuaciones',
                'verbose_name': 'Actuación',
            },
        ),
    ]
