# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-16 04:14
from __future__ import unicode_literals
from django.db import migrations, models
import django.db.models.deletion
import sorl.thumbnail.fields
import stats.models


class Migration(migrations.Migration):
    replaces = [('stats', '0001_initial'), ('stats', '0002_auto_20160420_2157'), ('stats', '0003_auto_20160421_2135'),
                ('stats', '0004_auto_20160421_2137'), ('stats', '0005_mainpictures'),
                ('stats', '0006_auto_20160423_2311'), ('stats', '0007_auto_20160515_2211'),
                ('stats', '0008_auto_20160516_0011')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fixture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=stats.models.get_next_fixture_date, help_text='Fecha de la jornada',
                                          unique=True, verbose_name='Fecha')),
                ('image',
                 sorl.thumbnail.fields.ImageField(blank=True, help_text='Foto de la jornada', upload_to='Jornadas',
                                                  verbose_name='Foto')),
                ('numero', models.PositiveSmallIntegerField(default=stats.models.get_next_fixture,
                                                            verbose_name='Jornada número')),
            ],
            options={
                'verbose_name': 'Jornada',
                'ordering': ['-date'],
                'verbose_name_plural': 'Jornadas',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name',
                 models.CharField(help_text='Nombre del jugador', max_length=200, unique=True, verbose_name='Nombre')),
                ('image',
                 sorl.thumbnail.fields.ImageField(blank=True, help_text='Foto del jugador', upload_to='Avatars',
                                                  verbose_name='Avatar')),
                ('games_played', models.PositiveSmallIntegerField(default=0, verbose_name='Juegos jugados')),
                ('wins', models.PositiveSmallIntegerField(default=0, verbose_name='Juegos ganados')),
                ('draws', models.PositiveSmallIntegerField(default=0, verbose_name='Juegos empatados')),
                ('losses', models.PositiveSmallIntegerField(default=0, verbose_name='Juegos perdidos')),
                ('goals', models.PositiveSmallIntegerField(default=0, verbose_name='Goles anotados')),
                ('assists', models.PositiveSmallIntegerField(default=0, verbose_name='Asistencias')),
                ('elo', models.DecimalField(decimal_places=5, default=0, max_digits=7, verbose_name='ELO')),
            ],
            options={
                'verbose_name': 'Jugador',
                'ordering': ['-elo'],
                'verbose_name_plural': 'Jugadores',
            },
        ),
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('games_played', models.PositiveSmallIntegerField(default=0, verbose_name='Juegos jugados')),
                ('wins', models.PositiveSmallIntegerField(default=0, verbose_name='Juegos ganados')),
                ('draws', models.PositiveSmallIntegerField(default=0, verbose_name='Juegos empatados')),
                ('losses', models.PositiveSmallIntegerField(default=0, verbose_name='Juegos perdidos')),
                ('goals', models.PositiveSmallIntegerField(default=0, verbose_name='Goles anotados')),
                ('assists', models.PositiveSmallIntegerField(default=0, verbose_name='Asistencias')),
                ('elo', models.DecimalField(decimal_places=5, default=0, max_digits=7, verbose_name='ELO')),
                ('fixture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats',
                                              to='stats.Fixture', verbose_name='Jornada')),
                ('player',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='stats.Player',
                                   verbose_name='Jugador')),
            ],
            options={
                'verbose_name': 'Actuación',
                'verbose_name_plural': 'Actuaciones',
            },
        ),
        migrations.AlterModelOptions(
            name='fixture',
            options={'ordering': ['-numero'], 'verbose_name': 'Jornada', 'verbose_name_plural': 'Jornadas'},
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(verbose_name='Numero')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
            ],
            options={
                'ordering': ['-number'],
                'verbose_name': 'Temporada',
                'verbose_name_plural': 'Temporadas',
            },
        ),
        migrations.AddField(
            model_name='fixture',
            name='season',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fixtures',
                                    to='stats.Season', verbose_name='Temporada'),
        ),
        migrations.AlterModelOptions(
            name='fixture',
            options={'ordering': ['-number'], 'verbose_name': 'Jornada', 'verbose_name_plural': 'Jornadas'},
        ),
        migrations.RenameField(
            model_name='fixture',
            old_name='numero',
            new_name='number',
        ),
        migrations.CreateModel(
            name='MainPictures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', sorl.thumbnail.fields.ImageField(upload_to='Main', verbose_name='Picture')),
            ],
            options={
                'verbose_name': 'Foto Portada',
                'verbose_name_plural': 'Fotos Portada',
            },
        ),
        migrations.AlterModelOptions(
            name='stats',
            options={'ordering': ['-elo'], 'verbose_name': 'Actuación', 'verbose_name_plural': 'Actuaciones'},
        ),
        migrations.AlterField(
            model_name='fixture',
            name='number',
            field=models.PositiveSmallIntegerField(default=stats.models.get_next_fixture, verbose_name='Jornada'),
        ),
        migrations.CreateModel(
            name='PlayerPerformance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fixture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performances',
                                              to='stats.Fixture', verbose_name='Jornada')),
            ],
            options={
                'verbose_name': 'Desempeño',
                'verbose_name_plural': 'Desempeños',
            },
        ),
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': ['name'], 'verbose_name': 'Jugador', 'verbose_name_plural': 'Jugadores'},
        ),
        migrations.RemoveField(
            model_name='player',
            name='assists',
        ),
        migrations.RemoveField(
            model_name='player',
            name='draws',
        ),
        migrations.RemoveField(
            model_name='player',
            name='elo',
        ),
        migrations.RemoveField(
            model_name='player',
            name='games_played',
        ),
        migrations.RemoveField(
            model_name='player',
            name='goals',
        ),
        migrations.RemoveField(
            model_name='player',
            name='losses',
        ),
        migrations.RemoveField(
            model_name='player',
            name='wins',
        ),
        migrations.RemoveField(
            model_name='stats',
            name='fixture',
        ),
        migrations.RemoveField(
            model_name='stats',
            name='player',
        ),
        migrations.AddField(
            model_name='player',
            name='global_stats',
            field=models.OneToOneField(default=None,
                                       help_text='Estadísticas totales del jugador. Incluye todas las temporadas',
                                       on_delete=django.db.models.deletion.CASCADE, to='stats.Stats',
                                       verbose_name='Estadísticas globales'),
        ),
        migrations.AddField(
            model_name='playerperformance',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performances',
                                    to='stats.Player', verbose_name='Jugaodr'),
        ),
        migrations.AddField(
            model_name='playerperformance',
            name='stat',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='stats.Stats',
                                       verbose_name='Estadística'),
        ),
        migrations.AlterUniqueTogether(
            name='playerperformance',
            unique_together=set([('player', 'fixture')]),
        ),
    ]
