# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-16 04:25
from __future__ import unicode_literals
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('stats', '0001_squashed_0008_auto_20160516_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='global_stats',
            field=models.OneToOneField(blank=True,
                                       help_text='Estadísticas totales del jugador. Incluye todas las temporadas',
                                       null=True, on_delete=django.db.models.deletion.CASCADE, to='stats.Stats',
                                       verbose_name='Estadísticas globales'),
        ),
    ]
