# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-21 01:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fixture',
            options={'ordering': ['-numero'], 'verbose_name': 'Jornada', 'verbose_name_plural': 'Jornadas'},
        ),
    ]
