# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-16 04:35
from __future__ import unicode_literals
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('stats', '0002_auto_20160516_0025'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fixture',
            options={'ordering': ['number'], 'verbose_name': 'Jornada', 'verbose_name_plural': 'Jornadas'},
        ),
    ]
