# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-22 01:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0003_auto_20160421_2135'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fixture',
            options={'ordering': ['-number'], 'verbose_name': 'Jornada', 'verbose_name_plural': 'Jornadas'},
        ),
        migrations.RenameField(
            model_name='fixture',
            old_name='numero',
            new_name='number',
        ),
    ]
