# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-16 05:28
from __future__ import unicode_literals
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('stats', '0003_auto_20160516_0035'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='fixture',
            unique_together=set([('number', 'season')]),
        ),
    ]
