# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-24 02:32
from __future__ import unicode_literals

from django.db import migrations, models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0004_auto_20160421_2137'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainPictures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', sorl.thumbnail.fields.ImageField(upload_to='Main', verbose_name='Picture')),
            ],
            options={
                'verbose_name_plural': 'Fotos Portada',
                'verbose_name': 'Foto Portada',
            },
        ),
    ]
