# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-24 03:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0005_mainpictures'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stats',
            options={'ordering': ['-elo'], 'verbose_name': 'Actuación', 'verbose_name_plural': 'Actuaciones'},
        ),
    ]
